services:
  - type: web
    name: realtime-messenger-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    root: server
  - type: static
    name: realtime-messenger-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    publishPath: client/dist
    root: client
